FROM python:3.5-alpine

RUN pip install Flask waitress
RUN mkdir /app
WORKDIR /app
COPY ./flask_app.py /app/
RUN addgroup -S usuariocontenedor && adduser -S -s /bin/false -G  usuariocontenedor usuariocontenedor  && chown -R usuariocontenedor:usuariocontenedor /app
USER usuariocontenedor
EXPOSE 5000
CMD ["python","flask_app.py"]