FROM python:3.5-alpine

RUN pip install Flask waitress
RUN mkdir /app
WORKDIR /app
COPY ./flask_app.py /app/
RUN apk add shadow && \
	/usr/sbin/groupadd -g 10001 --system usuariocontenedor && \
	/usr/sbin/useradd --system -u 10001 -s /bin/false -g  usuariocontenedor usuariocontenedor  && \
	chown -R usuariocontenedor:usuariocontenedor /app
USER usuariocontenedor
EXPOSE 5000
CMD ["python","flask_app.py"]